FROM node:18-alpine AS builder

WORKDIR /app

ARG REACT_APP_API_URL=/api
ARG REACT_APP_GOOGLE_CLIENT_ID
ARG REACT_APP_MANHWAS_PER_PAGE=4
ARG REACT_APP_SEARCH_PAGE_SIZE=4
ARG REACT_APP_ADMIN_MANHWAS_PER_PAGE=16
ARG REACT_APP_ADMIN_MANHWA_PROVIDER_PAGE_SIZE=16
ARG REACT_APP_RANDOM_MANHWAS_COUNT=8

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_MANHWAS_PER_PAGE=$REACT_APP_MANHWAS_PER_PAGE
ENV REACT_APP_SEARCH_PAGE_SIZE=$REACT_APP_SEARCH_PAGE_SIZE
ENV REACT_APP_ADMIN_MANHWAS_PER_PAGE=$REACT_APP_ADMIN_MANHWAS_PER_PAGE
ENV REACT_APP_ADMIN_MANHWA_PROVIDER_PAGE_SIZE=$REACT_APP_ADMIN_MANHWA_PROVIDER_PAGE_SIZE
ENV REACT_APP_RANDOM_MANHWAS_COUNT=$REACT_APP_RANDOM_MANHWAS_COUNT

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine AS production

COPY --from=builder /app/build /usr/share/nginx/html
COPY <<'EOF' /etc/nginx/conf.d/default.conf
server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
EOF

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
